//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 12:14:27 PM CEST 
//


package pl.coderstrust.invoices.model.soap;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="entry"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="vat" type="{http://spring.io/guides/gs-producing-web-service}vat"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entry", propOrder = {
    "id",
    "productName",
    "amount",
    "price",
    "vat"
})
public class Entry {

  protected long id;
  @XmlElement(required = true)
  protected String productName;
  @XmlElement(required = true)
  protected String amount;
  @XmlElement(required = true)
  protected BigDecimal price;
  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected Vat vat;

  /**
   * Gets the value of the id property.
   */
  public long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the productName property.
   *
   * @return possible object is {@link String }
   */
  public String getProductName() {
    return productName;
  }

  /**
   * Sets the value of the productName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setProductName(String value) {
    this.productName = value;
  }

  /**
   * Gets the value of the amount property.
   *
   * @return possible object is {@link String }
   */
  public String getAmount() {
    return amount;
  }

  /**
   * Sets the value of the amount property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAmount(String value) {
    this.amount = value;
  }

  /**
   * Gets the value of the price property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getPrice() {
    return price;
  }

  /**
   * Sets the value of the price property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setPrice(BigDecimal value) {
    this.price = value;
  }

  /**
   * Gets the value of the vat property.
   *
   * @return possible object is {@link Vat }
   */
  public Vat getVat() {
    return vat;
  }

  /**
   * Sets the value of the vat property.
   *
   * @param value allowed object is {@link Vat }
   */
  public void setVat(Vat value) {
    this.vat = value;
  }

}
