//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.23 at 04:12:30 PM CEST 
//


package pl.coderstrust.invoices.model.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.coderstrust.invoices.model.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: pl.coderstrust.invoices.model.soap
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Dummy }
   */
  public Dummy createDummy() {
    return new Dummy();
  }

  /**
   * Create an instance of {@link AddInvoiceRequest }
   */
  public AddInvoiceRequest createAddInvoiceRequest() {
    return new AddInvoiceRequest();
  }

  /**
   * Create an instance of {@link CompanySoap }
   */
  public CompanySoap createCompanySoap() {
    return new CompanySoap();
  }

  /**
   * Create an instance of {@link EntrySoap }
   */
  public EntrySoap createEntrySoap() {
    return new EntrySoap();
  }

  /**
   * Create an instance of {@link AddInvoiceResponse }
   */
  public AddInvoiceResponse createAddInvoiceResponse() {
    return new AddInvoiceResponse();
  }

  /**
   * Create an instance of {@link InvoiceSoap }
   */
  public InvoiceSoap createInvoiceSoap() {
    return new InvoiceSoap();
  }

  /**
   * Create an instance of {@link GetAllInvoicesRequest }
   */
  public GetAllInvoicesRequest createGetAllInvoicesRequest() {
    return new GetAllInvoicesRequest();
  }

  /**
   * Create an instance of {@link GetAllInvoicesResponse }
   */
  public GetAllInvoicesResponse createGetAllInvoicesResponse() {
    return new GetAllInvoicesResponse();
  }

  /**
   * Create an instance of {@link GetInvoiceRequest }
   */
  public GetInvoiceRequest createGetInvoiceRequest() {
    return new GetInvoiceRequest();
  }

  /**
   * Create an instance of {@link GetInvoiceResponse }
   */
  public GetInvoiceResponse createGetInvoiceResponse() {
    return new GetInvoiceResponse();
  }

  /**
   * Create an instance of {@link GetInvoicesBetweenDatesRequest }
   */
  public GetInvoicesBetweenDatesRequest createGetInvoicesBetweenDatesRequest() {
    return new GetInvoicesBetweenDatesRequest();
  }

  /**
   * Create an instance of {@link GetInvoicesBetweenDatesResponse }
   */
  public GetInvoicesBetweenDatesResponse createGetInvoicesBetweenDatesResponse() {
    return new GetInvoicesBetweenDatesResponse();
  }

  /**
   * Create an instance of {@link RemoveInvoiceRequest }
   */
  public RemoveInvoiceRequest createRemoveInvoiceRequest() {
    return new RemoveInvoiceRequest();
  }

  /**
   * Create an instance of {@link RemoveInvoiceResponse }
   */
  public RemoveInvoiceResponse createRemoveInvoiceResponse() {
    return new RemoveInvoiceResponse();
  }

}
